version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'

  discovery-service:
    image: discovery-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod'
    ports:
      - '8761:8761'

  zuul-service:
    image: zuul-service
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod'
    ports:
      - '8090:8090'

  organization-client:
    image: organization-client
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod'

  department-client:
    image: department-client
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod'

  employee-client:
    image: employee-client
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod'